custom_rules:
  doc_blocks:
    name: "Documentation Comment Format"
    regex: '(\/\*\*)'
    message: "Use `///` instead of `/** ... */` for documentation comments."
    severity: warning

disabled_rules:
  - force_try
  - force_cast
identifier_name:
  validates_start_with_lowercase: false
  excluded:
    - to
    - a
    - b
    - d
    - k
    - n
    - s
    - x
    - y
line_length:
  ignores_comments: true
