language: swift
os: osx
env: LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update && brew bundle
  - bundle install

jobs:
  include:
    - stage: test
      script: bundle exec fastlane test
      script: bundle exec fastlane lint
