language: swift
os: osx
osx_image: xcode10
env: LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
rvm: 2.0.0

addons:
  homebrew:
    update: true
    brewfile: true

before_install:
  - bundle install

before_script:
  - bundle exec danger

jobs:
  include:
    - stage: test
      name: testing
      script: bundle exec fastlane test
    - stage: test
      name: linting
      script: bundle exec fastlane lint
