language: swift
os: osx
osx_image: xcode10
env: LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

addons:
  homebrew:
    update: true
    brewfile: true

before_install:
  - bundle install

before_script:
  - bundle exec danger

jobs:
  include:
    - stage: test
      name: testing
      script: bundle exec fastlane test
    # Don'T lint the whole project now (#98)
    # - stage: test
    #   name: linting
    #   script: bundle exec fastlane lint
