language: swift
os: osx
osx_image: xcode10.2
env: LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

addons:
  homebrew:
    brewfile: true

before_install:
  - bundle install

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export PR_NUMBER=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo ""; else echo $TRAVIS_PULL_REQUEST; fi)

script:
  - bundle exec fastlane test
  - bundle exec danger
  - bundle exec sonarqube branch:$BRANCH pr_number:$PR_NUMBER
