language: swift
os: osx
osx_image: xcode10
env: LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

addons:
  homebrew:
    update: true
    brewfile: true

before_install:
  - bundle install

script:
  - bundle exec fastlane test
  - bundle exec fastlane danger
