language: swift
os: osx
osx_image: xcode11.2
env: LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

addons:
  homebrew:
    brewfile: true

before_install:
  - bundle install

script:
  - bundle exec fastlane test
  - bundle exec danger
